//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFGreenBean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int CourseId { get; set; }
        public string Code { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public string Term { get; set; }
        public string Prerequisite { get; set; }
        public string Description { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }


        public int DeleteCourse(int courseID)
        {
            // TO DO
            return 1;
        }
    }
}
